version: '3.2'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/postgresql.conf:/etc/postgresql/postgresql.conf
    restart: always

  s3:
    build:
      context: ./s3
    ports:
      - "9000:9000"
    environment:
      AWS_ACCESS_KEY_ID: ${S3_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${S3_SECRET_KEY}
    volumes:
      - ./s3/data:/data
    restart: always