version: '3.2'

services:
  postgres:
    image: postgres:latest
    env_file: devo.conf
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./sql/data:/data
    restart: always

  s3:
    image: minio/minio
    ports:
      - "127.0.0.1:9000:9000"
    env_file: devo.conf
    volumes:
      - ./s3/data:/data
    command: server /data
    restart: always
