version: '3.2'

services:
  postgres:
    image: postgres:latest
    env_file: devo.conf
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql/postgresql.conf:/etc/postgresql/postgresql.conf
    restart: always

  s3:
    image: minio/minio
    ports:
      - "9000:9000"
    env_file: devo.conf
    volumes:
      - ./s3/data:/data
    command: server /data
    restart: always
