version: '3'

services:
  s3:
    build:
      context: ./s3
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${S3_ACCESS_KEY}
      MINIO_SECRET_KEY: ${S3_SECRET_KEY}
    volumes:
      - ./s3/data:/data
    restart: always
